version: 2.1
#orbs:
#  docker: circleci/docker@1.5.0
commands:
  deploy:
    description: Log Docker agent into Quay.io
    steps:
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run: |
          docker build .
          docker-compose up -d
      - run:
          name: Check install works
          command: |
            URL='http://localhost:3000/'
            HTTP_STATUS="$(curl -IL --silent $URL | grep HTTP )";
            echo "${HTTP_STATUS}";
      - run:
          name: Cleanup
          command: |
            docker-compose down
jobs:
    build-image:
       docker:
         - image: cimg/base:2020.01
       steps: 
        - deploy
workflows:
  commit:
    jobs:
      - build-image
