version: 2.1
commands:
  deploy:
    description: Test and app using docker-compose
    steps:
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Deploy
          command: |
            docker-compose up -d
      -run:
          name: Stop
          commnd: docker-compose down
jobs:
    build-image:
       docker:
         - image: cimg/base:2020.01
       environment:
         TEST_RESULTS: /tmp/test-results
       steps: 
        - deploy
workflows:
  commit:
    jobs:
      - build-image
